name: Build and deploy .Net6

on:
  workflow_call:
#  push:
#    branches:
#      - master
env:
  PACKAGE_NAME: netsix-blazor-mvc-ef-ex
  
jobs: 
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#          
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: user/app:latest
    