name: Build and deploy ASP app to Azure Web App - man-old-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    env:
      PACKAGE_NAME: netsix-blazor-mvc-ef-ex
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version

      - name: Install dotnet dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build -c Release

      - name: Publish the project
        run: |
          dotnet publish -c Release -o ./published

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME}}
          path: "./published/**"

  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME}}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "app-appspoke-az-ince-dev-001"
          slot-name: "Production"
          publish-profile: ${{ secrets.APP_APPSPOKE_PUBLISHFILE }}
          package: .
